### ISSUE TITLE
体验感受

### ISSUE THREAD

**Issue by HzRr** [tomzhu0225/oral_practice_web_dev#2]
1.light主题下AI回答背景颜色与文字对比不高，难以辨认。
2.AI和Me said下方除了文字外是否能加上获取的语音播放的按钮，我这种基础差的人总想一句话多听几次。
3.因为没有visa卡注册不了azure，自己做了个腾讯云asr和tts的版本(速度有点慢)，能否pr到一个新branch

**Comment by tomzhu0225** [comment]
当然可以。随时可以提交pull request。另外如果解决web_RTC在中国不可用的问题，请问你有没有头绪。

**Comment by HzRr** [comment]
> 当然可以。随时可以提交pull request。另外如果解决web_RTC在中国不可用的问题，请问你有没有头绪。
webrtc我不是很懂，我是直接deploy到share.streamlit.io上的，如果在国内部署走全局代理应该可以吧？
