### ISSUE TITLE
这个怎么部署到vps

### ISSUE THREAD

**Issue by xinggonglie** [tomzhu0225/oral_practice_web_dev#4]
主站是费用已经用完了吗，pc没法使用，安卓也不行，1848839936@qq.com

**Comment by tomzhu0225** [comment]
哈喽，目前测试阶段已经告一段落。网站目前正在进行整改内容包括：加速语音识别过程；架设国内turn服务器；增加网站整体稳定性等内容。整改完成后，将发B站视频上线，谢谢支持！
另外，关于如何部署到其他服务器。理论上来说都是可行的。但是我主要部署再streamlit cloud上，所以不会发布关于部署在其他服务器上的内容。您可以自行修改代码来部署到您的服务器上。

**Comment by xinggonglie** [comment]
我没学过编程，有教程的话还能跟着操作。
你准备进行商业化了吗，我想进行线下的推广，试试商业模式能不能走通，你能不能加个账号系统，给我几个账号我推广试试，另外必须套魔法才能使用吗？这个挺麻烦的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午3:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomzhu0225/oral_practice_web_dev] 这个怎么部署到vps (Issue #4)




 
哈喽，目前测试阶段已经告一段落。网站目前正在进行整改内容包括：加速语音识别过程；架设国内turn服务器；增加网站整体稳定性等内容。整改完成后，将发B站视频上线，谢谢支持！
 另外，关于如何部署到其他服务器。理论上来说都是可行的。但是我主要部署再streamlit cloud上，所以不会发布关于部署在其他服务器上的内容。您可以自行修改代码来部署到您的服务器上。

**Comment by tomzhu0225** [comment]
在目前这种状况下，哪怕是整改完成后再度开放我也希望可以让所有人都能使用这个网站，来利用AI这个新事物练习口语。如你所见，源码是开源的。目前我收到的捐助（虽然不多），但也足以维系这个项目一段时间。另外添加账号系统需要额外的时间成本，是我这样的学生开发者目前所没有的。
能让更多人知道这个项目，参与开发才是我的目的。
如果网站整改完毕，我会回复您的！

**Comment by xinggonglie** [comment]
你是不准备采用付费模式吗，那能不能和我说下，开源的那个怎么部署到服务器，我这里报错了
整改大约需要几天，我先推广试试，后面有情况的我们再沟通



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午4:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomzhu0225/oral_practice_web_dev] 这个怎么部署到vps (Issue #4)




 
在目前这种状况下，哪怕是整改完成后再度开放我也希望可以让所有人都能使用这个网站，来利用AI这个新事物练习口语。如你所见，源码是开源的。目前我收到的捐助（虽然不多），但也足以维系这个项目一段时间。另外添加账号系统需要额外的时间成本，是我这样的学生开发者目前所没有的。
 能让更多人知道这个项目，参与开发才是我的目的。
 如果网站整改完毕，我会回复您的！

**Comment by xinggonglie** [comment]
要不我付费你帮我处理下吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午4:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomzhu0225/oral_practice_web_dev] 这个怎么部署到vps (Issue #4)




 
在目前这种状况下，哪怕是整改完成后再度开放我也希望可以让所有人都能使用这个网站，来利用AI这个新事物练习口语。如你所见，源码是开源的。目前我收到的捐助（虽然不多），但也足以维系这个项目一段时间。另外添加账号系统需要额外的时间成本，是我这样的学生开发者目前所没有的。
 能让更多人知道这个项目，参与开发才是我的目的。
 如果网站整改完毕，我会回复您的！

**Comment by tomzhu0225** [comment]
目前代码可以部署到streamlit cloud上。其他的我也没尝试过。整改需要较长时间。这个网站刚结束了第一轮测试，我建议您不要过于急切。另外我不支持付费来推进某项功能。您可以通过捐赠的方式来支持这个项目。
我想重申一下我制作这个项目的目的，让更多人能用上更低成本，更有效的练习口语的方法。重点不在于商业化。

请您稍安勿躁！

**Comment by xinggonglie** [comment]
刚才报错的那个图片页面就是streamlit，clone了web_dev的那个代码，另外输入gptapi和微软api key的地方在哪里，我实在不知道怎么部署了。
付费推广也不影响你的追求，看到付费效果好了，用的人自然会去找免费的用了，主要是我找了几个人都是做前端的，没有前后端都能做的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午4:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomzhu0225/oral_practice_web_dev] 这个怎么部署到vps (Issue #4)




 
目前代码可以部署到streamlit cloud上。其他的我也没尝试过。整改需要较长时间。这个网站刚结束了第一轮测试，我建议您不要过于急切。另外我不支持付费来推进某项功能。您可以通过捐赠的方式来支持这个项目。
 我想重申一下我制作这个项目的目的，让更多人能用上更低成本，更有效的练习口语的方法。重点不在于商业化。
 
请您稍安勿躁！

**Comment by tomzhu0225** [comment]
用的是streamlit的secret系统，自己去搜一下吧。我还有其他事情恕不能及时回复了（而且我这看不到图片）

**Comment by xinggonglie** [comment]
晚点再聊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomzhu0225/oral_practice_web_dev] 这个怎么部署到vps (Issue #4)




 
用的是streamlit的secret系统，自己去搜一下吧。我还有其他事情恕不能及时回复了（而且我这看不到图片）

**Comment by xinggonglie** [comment]
你好，我们也想做语音对话，用微软的语音，部署的服务器上一直出错，请问是哪里的问题？付费咨询也可以。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomzhu0225/oral_practice_web_dev] 这个怎么部署到vps (Issue #4)




 
用的是streamlit的secret系统，自己去搜一下吧。我还有其他事情恕不能及时回复了（而且我这看不到图片）
